UPDATE multilabel_label SET name = "Acropora_Branching", code_gcrmn= "ACB" , id_gbif=7673664 WHERE name="Acropore_branched"; 
UPDATE multilabel_class SET name = "Acropora_Branching" WHERE name="Acropore_branched"; 
UPDATE multilabel_label SET name = "Acropora_Digitate", code_gcrmn= "ACD" , id_gbif=7673664 WHERE name="Acropore_digitised"; 
UPDATE multilabel_class SET name = "Acropora_Digitate" WHERE name="Acropore_digitised"; 
UPDATE multilabel_label SET name = "Acropora_Submassive", code_gcrmn= "ACS" , id_gbif=7673664 WHERE name="Acropore_sub_massive"; 
UPDATE multilabel_class SET name = "Acropora_Submassive" WHERE name="Acropore_sub_massive"; 
UPDATE multilabel_label SET name = "Acropora_Tabular", code_gcrmn= "ACT" , id_gbif=7673664 WHERE name="Acropore_tabular"; 
UPDATE multilabel_class SET name = "Acropora_Tabular" WHERE name="Acropore_tabular"; 
UPDATE multilabel_label SET name = "Actinopyga_echinites", code_gcrmn=NULL, id_gbif=2279192 WHERE name="Actinopyga_echinites"; 
UPDATE multilabel_class SET name = "Actinopyga_echinites" WHERE name="Actinopyga_echinites"; 
UPDATE multilabel_label SET name = "Actinopyga_mauritiana", code_gcrmn=NULL, id_gbif=4343105 WHERE name="Actinopyga_mauritiana"; 
UPDATE multilabel_class SET name = "Actinopyga_mauritiana" WHERE name="Actinopyga_mauritiana"; 
UPDATE multilabel_label SET name = "Algae_Coralline", code_gcrmn= "AC" , id_gbif=670 WHERE name="Algae_limestone"; 
UPDATE multilabel_class SET name = "Algae_Coralline" WHERE name="Algae_limestone"; 
UPDATE multilabel_label SET name = "Algae_Halimeda", code_gcrmn= "AD" , id_gbif=NULL WHERE name="Algae_drawn_up"; 
UPDATE multilabel_class SET name = "Algae_Halimeda" WHERE name="Algae_drawn_up"; 
UPDATE multilabel_label SET name = "Algae_Turf", code_gcrmn= "AG" , id_gbif=NULL WHERE name="Algae_sodding"; 
UPDATE multilabel_class SET name = "Algae_Turf" WHERE name="Algae_sodding"; 
UPDATE multilabel_label SET name = "Algal_Assemblage", code_gcrmn= "AA" , id_gbif=NULL WHERE name="Algae_assembly"; 
UPDATE multilabel_class SET name = "Algal_Assemblage" WHERE name="Algae_assembly"; 
UPDATE multilabel_label SET name = "Ascidians", code_gcrmn= "AS" , id_gbif=2330492 WHERE name="Ascidia"; 
UPDATE multilabel_class SET name = "Ascidians" WHERE name="Ascidia"; 
UPDATE multilabel_label SET name = "Atra/Leucospilota", code_gcrmn=NULL, id_gbif=2279143 WHERE name="Atra/Leucospilota"; 
UPDATE multilabel_class SET name = "Atra/Leucospilota" WHERE name="Atra/Leucospilota"; 
UPDATE multilabel_label SET name = "Bleached_coral", code_gcrmn=NULL, id_gbif=714 WHERE name="Bleached_coral"; 
UPDATE multilabel_class SET name = "Bleached_coral" WHERE name="Bleached_coral"; 
UPDATE multilabel_label SET name = "Blurred", code_gcrmn=NULL, id_gbif=NULL WHERE name="Blurred"; 
UPDATE multilabel_class SET name = "Blurred" WHERE name="Blurred"; 
UPDATE multilabel_label SET name = "Bohadschia_vitiensis", code_gcrmn=NULL, id_gbif=5721580 WHERE name="Bohadschia_vitiensis"; 
UPDATE multilabel_class SET name = "Bohadschia_vitiensis" WHERE name="Bohadschia_vitiensis"; 
UPDATE multilabel_label SET name = "D_savignyi/S_variolaris/E_calamaris/E_diadema", code_gcrmn=NULL, id_gbif=221 WHERE name="D_savignyi/S_variolaris/E_calamaris/E_diadema"; 
UPDATE multilabel_class SET name = "D_savignyi/S_variolaris/E_calamaris/E_diadema" WHERE name="D_savignyi/S_variolaris/E_calamaris/E_diadema"; 
UPDATE multilabel_label SET name = "Dead_coral", code_gcrmn=NULL, id_gbif=NULL WHERE name="Dead_coral"; 
UPDATE multilabel_class SET name = "Dead_coral" WHERE name="Dead_coral"; 
UPDATE multilabel_label SET name = "Echinometra_mathaei", code_gcrmn=NULL, id_gbif=2278863 WHERE name="Echinometra_mathaei"; 
UPDATE multilabel_class SET name = "Echinometra_mathaei" WHERE name="Echinometra_mathaei"; 
UPDATE multilabel_label SET name = "Echinostrephus_molaris", code_gcrmn=NULL, id_gbif=4341563 WHERE name="Echinostrephus_molaris"; 
UPDATE multilabel_class SET name = "Echinostrephus_molaris" WHERE name="Echinostrephus_molaris"; 
UPDATE multilabel_label SET name = "Fish", code_gcrmn=NULL, id_gbif=NULL WHERE name="Fish"; 
UPDATE multilabel_class SET name = "Fish" WHERE name="Fish"; 
UPDATE multilabel_label SET name = "Giant_clam", code_gcrmn= "BE" , id_gbif=4372618 WHERE name="Clam"; 
UPDATE multilabel_class SET name = "Giant_clam" WHERE name="Clam"; 
UPDATE multilabel_label SET name = "Gorgonian", code_gcrmn= "GO" , id_gbif=9197  WHERE name="Gorgon"; 
UPDATE multilabel_class SET name = "Gorgonian" WHERE name="Gorgon"; 
UPDATE multilabel_label SET name = "Heterocentrotus_mamillatus", code_gcrmn=NULL, id_gbif=5842749 WHERE name="Heterocentrotus_mamillatus"; 
UPDATE multilabel_class SET name = "Heterocentrotus_mamillatus" WHERE name="Heterocentrotus_mamillatus"; 
UPDATE multilabel_label SET name = "Heterocentrotus_trigonarius", code_gcrmn=NULL, id_gbif=4341565 WHERE name="Heterocentrus_trigonarius"; 
UPDATE multilabel_class SET name = "Heterocentrotus_trigonarius" WHERE name="Heterocentrus_trigonarius"; 
UPDATE multilabel_label SET name = "Homo_Sapiens", code_gcrmn=NULL, id_gbif=NULL WHERE name="Homo_sapiens"; 
UPDATE multilabel_class SET name = "Homo_Sapiens" WHERE name="Homo_sapiens"; 
UPDATE multilabel_label SET name = "Human_object", code_gcrmn=NULL, id_gbif=NULL WHERE name="Human_object"; 
UPDATE multilabel_class SET name = "Human_object" WHERE name="Human_object"; 
UPDATE multilabel_label SET name = "Living_coral", code_gcrmn=NULL, id_gbif=714 WHERE name="Living_coral"; 
UPDATE multilabel_class SET name = "Living_coral" WHERE name="Living_coral"; 
UPDATE multilabel_label SET name = "Non-acropora_Branching", code_gcrmn= "CB" , id_gbif=714 WHERE name="No_acropore_branched"; 
UPDATE multilabel_class SET name = "Non-acropora_Branching" WHERE name="No_acropore_branched"; 
UPDATE multilabel_label SET name = "Non-acropora_Coral_free", code_gcrmn= "CL" , id_gbif=714 WHERE name="No_acropore_solitary"; 
UPDATE multilabel_class SET name = "Non-acropora_Coral_free" WHERE name="No_acropore_solitary"; 
UPDATE multilabel_label SET name = "Non-acropora_Encrusting", code_gcrmn= "CE" , id_gbif=714 WHERE name="No_acropore_encrusting"; 
UPDATE multilabel_class SET name = "Non-acropora_Encrusting" WHERE name="No_acropore_encrusting"; 
UPDATE multilabel_label SET name = "Non-acropora_Foliose", code_gcrmn= "CF" , id_gbif=714 WHERE name="No_acropore_foliaceous"; 
UPDATE multilabel_class SET name = "Non-acropora_Foliose" WHERE name="No_acropore_foliaceous"; 
UPDATE multilabel_label SET name = "Non-acropora_Massive", code_gcrmn= "CM" , id_gbif=714 WHERE name="No_acropore_massive"; 
UPDATE multilabel_class SET name = "Non-acropora_Massive" WHERE name="No_acropore_massive"; 
UPDATE multilabel_label SET name = "Non-acropora_Millepora", code_gcrmn= "MI" , id_gbif=714 WHERE name="Millepore"; 
UPDATE multilabel_class SET name = "Non-acropora_Millepora" WHERE name="Millepore"; 
UPDATE multilabel_label SET name = "Non-acropora_Submassive", code_gcrmn= "CS" , id_gbif=714 WHERE name="No_acropore_sub_massive"; 
UPDATE multilabel_class SET name = "Non-acropora_Submassive" WHERE name="No_acropore_sub_massive"; 
UPDATE multilabel_label SET name = "Other_starfish", code_gcrmn= "ET" , id_gbif=214 WHERE name="Other_starfish"; 
UPDATE multilabel_class SET name = "Other_starfish" WHERE name="Other_starfish"; 
UPDATE multilabel_label SET name = "Rock", code_gcrmn= "RO" , id_gbif=NULL WHERE name="Rock"; 
UPDATE multilabel_class SET name = "Rock" WHERE name="Rock"; 
UPDATE multilabel_label SET name = "Rubble", code_gcrmn= "DEB" , id_gbif=NULL WHERE name="Rubble"; 
UPDATE multilabel_class SET name = "Rubble" WHERE name="Rubble"; 
UPDATE multilabel_label SET name = "Sand", code_gcrmn= "SA" , id_gbif=NULL WHERE name="Sand"; 
UPDATE multilabel_class SET name = "Sand" WHERE name="Sand"; 
UPDATE multilabel_label SET name = "Sea_anemone", code_gcrmn= "AN" , id_gbif=705 WHERE name="Anemone"; 
UPDATE multilabel_class SET name = "Sea_anemone" WHERE name="Anemone"; 
UPDATE multilabel_label SET name = "Sea_cucumber", code_gcrmn=NULL, id_gbif=2279143 WHERE name="Sea_cucumber"; 
UPDATE multilabel_class SET name = "Sea_cucumber" WHERE name="Sea_cucumber"; 
UPDATE multilabel_label SET name = "Sea_urchin", code_gcrmn= "OU" , id_gbif=221 WHERE name="Sea_urchins"; 
UPDATE multilabel_class SET name = "Sea_urchin" WHERE name="Sea_urchins"; 
UPDATE multilabel_label SET name = "Stichopus_chloronotus", code_gcrmn=NULL, id_gbif=4343242 WHERE name="Sichopus_chloronotus"; 
UPDATE multilabel_class SET name = "Stichopus_chloronotus" WHERE name="Sichopus_chloronotus"; 
UPDATE multilabel_label SET name = "Soft_coral", code_gcrmn= "CMO" , id_gbif=43 WHERE name="Soft_coral"; 
UPDATE multilabel_class SET name = "Soft_coral" WHERE name="Soft_coral"; 
UPDATE multilabel_label SET name = "Sponges", code_gcrmn= "EP" , id_gbif=105 WHERE name="Sponge"; 
UPDATE multilabel_class SET name = "Sponges" WHERE name="Sponge"; 
UPDATE multilabel_label SET name = "Synapta_maculata", code_gcrmn=NULL, id_gbif=5721258 WHERE name="Synapta_maculata"; 
UPDATE multilabel_class SET name = "Synapta_maculata" WHERE name="Synapta_maculata"; 
UPDATE multilabel_label SET name = "Syringodium_isoetifolium", code_gcrmn=NULL, id_gbif=2864078 WHERE name="Syringodium_isoetifolium"; 
UPDATE multilabel_class SET name = "Syringodium_isoetifolium" WHERE name="Syringodium_isoetifolium"; 
UPDATE multilabel_label SET name = "Thalassodendron_ciliatum", code_gcrmn=NULL, id_gbif=5328510 WHERE name="Thalassodendron_ciliatum"; 
UPDATE multilabel_class SET name = "Thalassodendron_ciliatum" WHERE name="Thalassodendron_ciliatum"; 
UPDATE multilabel_label SET name = "Thorny_starfish", code_gcrmn= "AP" , id_gbif=2271207 WHERE name="Acanthasters"; 
UPDATE multilabel_class SET name = "Thorny_starfish" WHERE name="Acanthasters"; 
UPDATE multilabel_label SET name = "Toxopneustes_pileolus", code_gcrmn=NULL, id_gbif=4341617 WHERE name="Toxopneustes_pileolus"; 
UPDATE multilabel_class SET name = "Toxopneustes_pileolus" WHERE name="Toxopneustes_pileolus"; 
UPDATE multilabel_label SET name = "Trample", code_gcrmn=NULL, id_gbif=NULL WHERE name="Trample"; 
UPDATE multilabel_class SET name = "Trample" WHERE name="Trample"; 
UPDATE multilabel_label SET name = "Tripneustes_gratilla", code_gcrmn=NULL, id_gbif=4341500 WHERE name="Tripneustes_gratilla"; 
UPDATE multilabel_class SET name = "Tripneustes_gratilla" WHERE name="Tripneustes_gratilla"; 
UPDATE multilabel_label SET name = "Turtle", code_gcrmn=NULL, id_gbif=11418114 WHERE name="Turtle"; 
UPDATE multilabel_class SET name = "Turtle" WHERE name="Turtle"; 
UPDATE multilabel_label SET name = "Useless", code_gcrmn=NULL, id_gbif=NULL WHERE name="Useless"; 
UPDATE multilabel_class SET name = "Useless" WHERE name="Useless"; 
UPDATE multilabel_label SET name = "Waste", code_gcrmn=NULL, id_gbif=NULL WHERE name="Waste"; 
UPDATE multilabel_class SET name = "Waste" WHERE name="Waste"; 