name: Build and push Docker monitoring

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Use Custom .dockerignore
      run: cp Dockerfile.monitoring.dockerignore .dockerignore
    
    - name: Build and push zenodo-monitoring to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.monitoring
        push: true
        tags: seatizendoi/zenodo-monitoring:latest
    
    - name: Cleanup .dockerignore
      run: rm .dockerignore
    
    - name: Use Custom .dockerignore
      run: cp Dockerfile.manager.dockerignore .dockerignore
    
    - name: Build and push zenodo-manager to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.manager
        push: true
        tags: seatizendoi/zenodo-manager:latest
    
    - name: Cleanup .dockerignore
      run: rm .dockerignore
      