name: Zenodo tools CI pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: zenodo_env
        environment-file: zenodo_env.yml
        auto-activate-base: true
    - run: |
        conda init
        conda activate zenodo_env
        conda info
        conda list
        conda env list


    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*_test.py"