name: Zenodo tools CI pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11  # This can be removed as it's specified in your environment file
    
    - name: Create environment from .yml file
      run: conda env create -f environment.yml
  
    - name: Activate Conda environment
      run: conda activate zenodo_env

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*_test.py"